# Generated by Django 3.0.1 on 2019-12-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='onwer',
            new_name='ower',
        ),
    ]
