# Generated by Django 3.0.1 on 2019-12-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20200101_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ower',
            new_name='owner',
        ),
    ]
